name: Sixie Yu
description: Personal website
menu:
 - page: Research
   url: /research
   #- page: Awards
   #url: /awards
   #menu_external:
   # - title: LinkedIn
   #   url: "https://www.linkedin.com/in/sixie-yu-b6584187/"
mathjax: true
markdown: kramdown
encoding: utf-8
# baseurl: "marsplus.github.io"
baseurl: ""
locale: en_GB

sass:
  sass_dir: css
  style:    expanded
